--Updating Register_Customer
create or replace PROCEDURE Register_Customer(FN IN CUSTOMER.FIRSTNAME%type, LN IN CUSTOMER.LASTNAME%type,ADDRESS IN CUSTOMER.STREETADDRESS%type,
                                              CITY IN CUSTOMER.CITY%type, STATE IN CUSTOMER.STATE%type, PHONE IN CUSTOMER.MOBILENUMBER%type, ID OUT CUSTOMER.CUSTOMERID%type)
   
IS
NID CUSTOMER.CUSTOMERID%TYPE;

BEGIN
  NID:= TEST_SEQ.NEXTVAL;
  
  INSERT INTO CUSTOMER(CUSTOMERID,FIRSTNAME,LASTNAME,STREETADDRESS,CITY,STATE,MOBILENUMBER)
  VALUES(NID,FN,LN,ADDRESS,CITY,STATE,PHONE);
  
  SELECT NID INTO ID
  FROM CUSTOMER
  WHERE NID = CUSTOMERID;
   DBMS_OUTPUT.PUT_LINE('The new customer has been successfully registered, Customer ID is: ' || ID);
END; 

--Test Register_Customer with out parameter
SET SERVEROUTPUT ON;
DECLARE N_ID CUSTOMER.CUSTOMERID%TYPE;
BEGIN  
REGISTER_CUSTOMER('Drake','Parker','2839 Abigail Road','Atlanta','GA','3224325647',N_ID);
DBMS_OUTPUT.PUT_LINE(N_ID);
END;

--UPDATING FIND_FLIGHT
CREATE OR REPLACE PROCEDURE Find_Flight(SRC IN FLIGHT.AIRPORTID%type,DST IN FLIGHT.DESTINATIONID%type,DT IN FLIGHT.FLIGHTDATE%type,
                                        CUR_FLIGHTS OUT SYS_REFCURSOR, FNUM OUT FLIGHT.FLIGHTID%type, AMNT OUT FLIGHT.FARE%type, OSEATS OUT FLIGHT.REMAINING_SEATS%type)
IS
--V_SOURCE      FLIGHT.AIRPORTID%type;
--V_DESTINATION FLIGHT.DESTINATIONID%type;
--V_DATE        FLIGHT.FLIGHTDATE%TYPE;

BEGIN
  OPEN CUR_FLIGHTS FOR
   SELECT FLIGHTID,FARE,REMAINING_SEATS
   FROM FLIGHT
   WHERE AIRPORTID = SRC AND DESTINATIONID = DST AND FLIGHTDATE = DT;

  -- LOOP
    --FETCH CUR_FLIGHTS INTO FNUM,V_SOURCE,V_DESTINATION,AMNT,V_DATE,OSEATS;
    --EXIT WHEN CUR_FLIGHTS%NOTFOUND;  
    --USE THIS TO CHECK WHEN ON SQL DEVELOPER/ OTHERWISE WONT RUN ON SITE
    --DBMS_OUTPUT.PUT_LINE('FLIGHT ID: '|| FNUM || ' SOURCE: ' || V_SOURCE || ' DESTINATION: ' || V_DESTINATION || ' FARE: $' || AMNT || 
      --                   ' DATE: ' || V_DATE || ' AVAILABLE SEATING: ' || OSEATS);
   --END LOOP;
  --CLOSE CUR_FLIGHTS;
END;

--USE TO TEST FIND_FLIGHT
SET SERVEROUTPUT ON;
DECLARE
CUR_FLIGHTS SYS_REFCURSOR;
FNUM FLIGHT.FLIGHTID%type;
AMNT FLIGHT.FARE%type;
OSEATS FLIGHT.REMAINING_SEATS%type;
BEGIN
FIND_FLIGHT('AA1','CC1','10-MAY-22',CUR_FLIGHTS,FNUM,AMNT,OSEATS);
LOOP
 FETCH CUR_FLIGHTS 
 INTO FNUM,AMNT,OSEATS;
 EXIT WHEN CUR_FLIGHTS%NOTFOUND; 
    DBMS_OUTPUT.PUT_LINE('FLIGHT ID: ' || FNUM || ' FARE: $' || AMNT || ' AVAILABLE SEATING: ' || OSEATS);
 END LOOP;                       
END;

--Updating Make_A_Reservation
create or replace PROCEDURE MAKE_A_RESERVATION(CUSTID IN RESERVATION.CUSTOMERID%type, FLYID IN RESERVATION.FLIGHTID%type,
                                               SEATS IN RESERVATION.SEATS_CONFIRMED%type, CONF OUT RESERVATION.CONFIRMATIONID%type)
IS
NCONF RESERVATION.CONFIRMATIONID%TYPE;

BEGIN
 
 NCONF:= TEST_SEQ.NEXTVAL;
 
 INSERT INTO RESERVATION(CONFIRMATIONID,CUSTOMERID,FLIGHTID,SEATS_CONFIRMED)
 VALUES(NCONF,CUSTID,FLYID,SEATS);
 
 SELECT NCONF INTO CONF
 FROM RESERVATION
 WHERE NCONF = CONFIRMATIONID;
 DBMS_OUTPUT.PUT_LINE('The customer ' || CUSTID || ' has made the reservation on flight ' || FLYID || ' with ' || SEATS || ' seats confirmed. Your confirmation number is ' || CONF || ' ');
END;

--Testing Make_A_Reservation with out parameter
SET SERVEROUTPUT ON;
DECLARE CONF RESERVATION.CONFIRMATIONID%TYPE;
BEGIN  
MAKE_A_RESERVATION('24','5','3',CONF);
DBMS_OUTPUT.PUT_LINE(CONF);
END;

--UPDATING VIEW_CUSTOMER_RESERVATION
CREATE OR REPLACE PROCEDURE View_Customer_Reservation(CUSTID IN RESERVATION.CUSTOMERID%type, CUR_CUSRES OUT SYS_REFCURSOR , CONF OUT RESERVATION.CONFIRMATIONID%TYPE, 
                                                      FN OUT CUSTOMER.FIRSTNAME%TYPE, LN OUT CUSTOMER.LASTNAME%TYPE, FLID OUT RESERVATION.FLIGHTID%TYPE, STS OUT RESERVATION.SEATS_CONFIRMED%TYPE)
IS

BEGIN

 OPEN CUR_CUSRES FOR
  SELECT RESERVATION.CONFIRMATIONID,CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME,RESERVATION.FLIGHTID,RESERVATION.SEATS_CONFIRMED 
  FROM RESERVATION,CUSTOMER
  WHERE CUSTOMER.CUSTOMERID = CUSTID AND CUSTOMER.CUSTOMERID = RESERVATION.CUSTOMERID;
  --LOOP
    --FETCH CUR_CUSRES INTO CONF,FN,LN,FLID,STS;
    --EXIT WHEN CUR_CUSRES%NOTFOUND; 
    --USE THIS TO CHECK WHEN ON SQL DEVELOPER/ OTHERWISE WONT RUN ON SITE
    --DBMS_OUTPUT.PUT_LINE('CONFIMATION NUMBER: ' || CONF || ' NAME: ' || FN || ' ' || LN || 
      --                   ' FLIGHTID: ' || FLID || ' SEATS CONFIRMED: ' || STS);
  --END LOOP;                       
END;

--USE TO TEST VIEW_CUSTOMER_RESERVATION
SET SERVEROUTPUT ON;
DECLARE
CUR_CUSRES SYS_REFCURSOR;
CONF RESERVATION.CONFIRMATIONID%TYPE;
FN CUSTOMER.FIRSTNAME%TYPE;
LN CUSTOMER.LASTNAME%TYPE;
FLID RESERVATION.FLIGHTID%TYPE;
STS RESERVATION.SEATS_CONFIRMED%TYPE;
BEGIN
view_customer_reservation('24',CUR_CUSRES,CONF,FN,LN,FLID,STS);
LOOP
 FETCH CUR_CUSRES 
 INTO CONF,FN,LN,FLID,STS;
 EXIT WHEN CUR_CUSRES%NOTFOUND; 
    DBMS_OUTPUT.PUT_LINE('CONFIMATION NUMBER: ' || CONF || ' NAME: ' || FN || ' ' || LN || 
                         ' FLIGHTID: ' || FLID || ' SEATS CONFIRMED: ' || STS);
 END LOOP;                       
END;